language: objective-c
osx_image: xcode7.2

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail 
  - xcodebuild -workspace aerogear-otp.ios.xcworkspace -scheme aerogear-otp.iosTests -sdk iphonesimulator -destination "OS=9.0,name=iPhone 6 Plus" -configuration Release test

notifications:
  irc: "irc.freenode.org#aerogear"
  
branches:
  only:
    - master
